# Name and timezone
name = "Plexactyl"
timezone = "Europe/London"
icon = "https://avatars.githubusercontent.com/u/176057729"

# Plexactyl release information
version = "18.0.5"

# Additional settings
testing = false
clusters = 1 # How many threads to use for multithreading
database = "sqlite://database.sqlite"

# Pterodactyl settings
[pterodactyl]
domain = "https://panel.example.com"
key = "PTERO_KEY"

# Webserver
[website]
port = 3_000

# Module settings (formerly API)
[api.client]

  [api.client.api]
  enabled = false
  code = "API_KEY"

# Frontend for j4r is unavailable.
  [api.client.j4r]
  enabled = false

    [[api.client.j4r.ads]]
    name = "Example server 1"
    invite = "https://discord.gg/example"
    id = "000000000000000000"
    coins = 200

    [[api.client.j4r.ads]]
    name = "Example server 2"
    invite = "https://discord.gg/example"
    id = "000000000000000000"
    coins = 200

  [api.client.bot]
  token = "BOT_TOKEN"

    [api.client.bot.joinguild]
    _comment = "The Discord bot must be in these servers and have invite permissions. Automatic guild joining will not work unless role packages are configured correctly. You can always just set it to a random role & package so that only this works."
    enabled = true
    guildid = []

    [api.client.bot.giverole]
    _comment = "Auto-join must be enabled for this to work - or the user must already be in your Discord. This will give the user a role when they login."
    enabled = true
    guildid = ""
    roleid = ""

  [api.client.passwordgenerator]
  signup = true
  note = "Use this to disable registering on Plexactyl."
  length = 16

  [api.client.allow]
  newusers = true
  regen = true
  overresourcessuspend = false

    [api.client.allow.server]
    create = true
    modify = true
    delete = true

  [api.client.oauth2]
  _comment = "Go to https://discord.dev/ and create an application to set up OAuth2. This is required for Plexactyl to work. You must also set the redirect URL to the link below."
  id = ""
  secret = ""
  link = "http://localhost:3000"
  callbackpath = "/callback"
  prompt = true

    [api.client.oauth2.ip]
    "trust x-forwarded-for" = true
    block = [ ]
    "duplicate check" = false
    _note = "Anti-alt checks will not work if you are proxying through Cloudflare. This is due to the fact that Cloudflare does not pass the real IP address through the headers. If you are using Cloudflare, please disable this feature."

  [api.client.ratelimits]
  "/callback" = 2
  "/create" = 1
  "/delete" = 1
  "/modify" = 1
  "/updateinfo" = 1
  "/setplan" = 2
  "/admin" = 1
  "/regen" = 1
  "/renew" = 1
  "/api/userinfo" = 1
  
  [api.client.packages]
  default = "default"

# Packages
[api.client.packages.list.default]
ram = 2_048
disk = 10_240
cpu = 150
servers = 2

    [api.client.packages.rolePackages]
    note = "This allows you to set a different plan/package to people who have a specific role however this requires the Discord bot to be configured and functioning. This is mainly used for Boost rewards."
    roleServer = ""

      [api.client.packages.rolePackages.roles]

[api.client.locations.1]
name = "Example Location"

# Use my optimized docker images! ghcr.io/zenllc/java:21 for java 21 or ghcr.io/zenllc/java:17 for java 17!

[api.client.eggs.purpur]
display = "Minecraft - Purpur"

  [api.client.eggs.purpur.minimum]
  ram = 1_024
  disk = 1_024
  cpu = 100

  [api.client.eggs.purpur.maximum]

  [api.client.eggs.purpur.info]
  egg = 5
  docker_image = "ghcr.io/zenllc/java:21"
  startup = "java -Xms256M -Xmx{{SERVER_MEMORY}}M {{JAVA_ARGUMENTS}} -jar {{SERVER_JARFILE}} --nogui"

    [api.client.eggs.purpur.info.environment]
    SERVER_JARFILE = "server.jar"
    BUILD_NUMBER = "latest"
    JAVA_ARGUMENTS = "--add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs/ -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 --add-modules=jdk.incubator.vector"

    [api.client.eggs.purpur.info.feature_limits]
    databases = 4
    backups = 4

  [api.client.coins]
  enabled = true

    [api.client.coins.store]
    enabled = true

      [api.client.coins.store.ram]
      cost = 300
      per = 1_024

      [api.client.coins.store.disk]
      cost = 200
      per = 5_120

      [api.client.coins.store.cpu]
      cost = 350
      per = 100

      [api.client.coins.store.servers]
      cost = 100
      per = 2

[api.afk]
_note = "This is the 2nd-generation version of Plexactyl's AFK system. Please report any bugs on the GitHub (github.com/plexactyl/panel). Thank you."
path = "ws"
every = 60
coins = 2.5
enabled = true

[linkvertise]
_note = "This is the 2nd-generation version of Plexactyl's AFK system. Please report any bugs on the GitHub (github.com/plexactyl/panel). Thank you."
enabled = true
coins = 30
userid = "000000"

[antivpn]
note = "For this to work, generate an API Key on https://proxycheck.io/. If you do not put a key, Plexactyl will automatically disable anti-VPN."
status = false
APIKey = "Proxycheck API Key"
whitelistedIPs = [ "IP address" ]

[whitelist]
note = "This allows only specific people to be able to login to the Plexactyl dashboard. This does not affect your Panel."
status = false
users = [ "User ID" ]

[logging]
_note = "This is the 2nd-generation version of Plexactyl's logging system. Please report any bugs on the GitHub (github.com/plexactyl/panel). Thank you."
status = false
webhook = "Webhook URL"

[logging.actions.user]
signup = true
"create server" = true
"gifted coins" = true
"modify server" = true
"buy servers" = true
"buy ram" = true
"buy cpu" = true
"buy disk" = true

[logging.actions.admin]
"set coins" = true
"add coins" = true
"set resources" = true
"set plan" = true
"create coupon" = true
"revoke coupon" = true
"remove account" = true
"view ip" = true
